export interface PresetConfig {
  layout: 'teeth' | 'tricolor' | 'circle' | 'double' | 'seal';
  stateName: string;
  slogan: string;
  primaryColor: string;
  textColorClass: string;
  borderColorClass: string;
  fillColorClass: string;
  borderHex: string;
  teethColorHex: string;
  liaisonTitle: string;
  liaisonAddressLines: string[];
  bannerColors?: string[];
  crestEmoji?: string;
  traditionalRulerFallback: string;
  stampText: string;
  stampColorClass: string;
  sealColorHex?: string;
}

export const PRESETS_DB: Record<string, PresetConfig> = {
  'Imo Heartland (Green teeth border)': {
    layout: 'teeth',
    stateName: 'IMO STATE',
    slogan: 'EASTERN HEARTLAND',
    primaryColor: '#006e4a',
    textColorClass: 'text-emerald-850',
    borderColorClass: 'border-emerald-850',
    fillColorClass: 'fill-emerald-800',
    borderHex: '#006e4a',
    teethColorHex: '#006e4a',
    liaisonTitle: 'IMO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 1240 MONROVIA STREET,', 'WUSE II,', 'ABUJA', 'TEL: 09-4130224'],
    crestEmoji: '🦁',
    traditionalRulerFallback: 'HRH Eze Anthony Njoku',
    stampText: 'IMO LIAISON',
    stampColorClass: 'border-red-500/35 text-red-500/40'
  },
  'Lagos Epe Style (Tri-color banner)': {
    layout: 'tricolor',
    stateName: 'LAGOS STATE',
    slogan: 'CENTRE OF EXCELLENCE',
    primaryColor: '#0284c7',
    textColorClass: 'text-[#1d3a5f]',
    borderColorClass: 'border-[#1d3a5f]',
    fillColorClass: 'fill-[#0284c7]',
    borderHex: '#0284c7',
    teethColorHex: '#0284c7',
    liaisonTitle: 'LAGOS STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 27 OYINKAN ABAYOMI DRIVE,', 'IKOYI,', 'LAGOS', 'TEL: 01-2702030'],
    bannerColors: ['#0284c7', '#dc2626', '#16a34a'],
    crestEmoji: '🌴',
    traditionalRulerFallback: 'HRH Oba of Lagos',
    stampText: 'LAGOS GOVT',
    stampColorClass: 'border-purple-500/40 text-purple-600/50'
  },
  'Oguta Classic (Double green circle)': {
    layout: 'circle',
    stateName: 'IMO STATE',
    slogan: 'EASTERN HEARTLAND',
    primaryColor: '#047857',
    textColorClass: 'text-emerald-900',
    borderColorClass: 'border-emerald-600',
    fillColorClass: 'fill-emerald-750',
    borderHex: '#047857',
    teethColorHex: '#047857',
    liaisonTitle: 'OGUTA ADMINISTRATIVE COUNCIL',
    liaisonAddressLines: ['LGA SECRETARIAT ROAD,', 'OGUTA,', 'IMO STATE', 'TEL: 083-421033'],
    crestEmoji: '🔱',
    traditionalRulerFallback: 'HRH Eze Anthony Njoku',
    stampText: 'OGUTA CLASSIC',
    stampColorClass: 'border-emerald-600/35 text-emerald-600/40'
  },
  'Cross River Ikom (Dual royal blue border)': {
    layout: 'double',
    stateName: 'CROSS RIVER STATE',
    slogan: 'THE NATION\'S PARADISE',
    primaryColor: '#1e3a8a',
    textColorClass: 'text-blue-900',
    borderColorClass: 'border-[#1e3a8a]',
    fillColorClass: 'fill-[#1e3a8a]',
    borderHex: '#1e3a8a',
    teethColorHex: '#1e3a8a',
    liaisonTitle: 'CROSS RIVER LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 1024 COCONUT STREET,', 'WUSE ZONE 4,', 'ABUJA', 'TEL: 09-5140130'],
    crestEmoji: '🌊',
    traditionalRulerFallback: 'HRH Obong of Calabar',
    stampText: 'CR STAT',
    stampColorClass: 'border-blue-500/35 text-blue-500/40'
  },
  'Ondo East Authentic (Red seal, light watermark)': {
    layout: 'seal',
    stateName: 'ONDO STATE',
    slogan: 'SUNSHINE STATE',
    primaryColor: '#b91c1c',
    textColorClass: 'text-red-750',
    borderColorClass: 'border-neutral-800',
    fillColorClass: 'fill-[#b91c1c]',
    borderHex: '#b91c1c',
    teethColorHex: '#b91c1c',
    liaisonTitle: 'ONDO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 43 MONROVIA ROAD,', 'WUSE II,', 'ABUJA', 'TEL: 09-3120412'],
    crestEmoji: '☀️',
    traditionalRulerFallback: 'HRH Deji of Akure',
    stampText: 'ONDO EAST',
    stampColorClass: 'border-red-500/35 text-red-500/40',
    sealColorHex: '#b91c1c'
  },
  'Abia Authentic (Double gold border)': {
    layout: 'double',
    stateName: 'ABIA STATE',
    slogan: 'GOD\'S OWN STATE',
    primaryColor: '#b45309',
    textColorClass: 'text-amber-900',
    borderColorClass: 'border-amber-600',
    fillColorClass: 'fill-amber-700',
    borderHex: '#b45309',
    teethColorHex: '#b45309',
    liaisonTitle: 'ABIA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 14 HOMELAND CRESCENT,', 'GARKI II,', 'ABUJA'],
    crestEmoji: '🌾',
    traditionalRulerFallback: 'HRH Eze Ikechi',
    stampText: 'ABIA GOVT',
    stampColorClass: 'border-amber-500/35 text-amber-500/40'
  },
  'Adamawa Savannah (Brown border)': {
    layout: 'seal',
    stateName: 'ADAMAWA STATE',
    slogan: 'LAND OF BEAUTY',
    primaryColor: '#7c2d12',
    textColorClass: 'text-orange-950',
    borderColorClass: 'border-orange-900',
    fillColorClass: 'fill-orange-800',
    borderHex: '#7c2d12',
    teethColorHex: '#7c2d12',
    liaisonTitle: 'ADAMAWA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 82 SAVANNAH WAY,', 'MAITAMA,', 'ABUJA'],
    crestEmoji: '⛰️',
    traditionalRulerFallback: 'HRH Lamido of Adamawa',
    stampText: 'ADAMAWA CERT',
    stampColorClass: 'border-orange-500/35 text-orange-550/40',
    sealColorHex: '#7c2d12'
  },
  'Akwa Ibom Dakkada (Orange banner)': {
    layout: 'tricolor',
    stateName: 'AKWA IBOM STATE',
    slogan: 'LAND OF PROMISE',
    primaryColor: '#ea580c',
    textColorClass: 'text-orange-900',
    borderColorClass: 'border-orange-700',
    fillColorClass: 'fill-orange-600',
    borderHex: '#ea580c',
    teethColorHex: '#ea580c',
    liaisonTitle: 'AKWA IBOM STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 99 DAKKADA WAY,', 'MAITAMA,', 'ABUJA'],
    bannerColors: ['#ea580c', '#ffffff', '#047857'],
    crestEmoji: '🦅',
    traditionalRulerFallback: 'HRH Edidem of Calabar',
    stampText: 'AKWA IBOM',
    stampColorClass: 'border-orange-500/40 text-orange-600/50'
  },
  'Anambra Light of the Nation (Gold crest)': {
    layout: 'double',
    stateName: 'ANAMBRA STATE',
    slogan: 'LIGHT OF THE NATION',
    primaryColor: '#d97706',
    textColorClass: 'text-amber-900',
    borderColorClass: 'border-amber-600',
    fillColorClass: 'fill-amber-700',
    borderHex: '#d97706',
    teethColorHex: '#d97706',
    liaisonTitle: 'ANAMBRA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 15 NIGER ROAD,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '💡',
    traditionalRulerFallback: 'HRH Igwe of Onitsha',
    stampText: 'ANAMBRA',
    stampColorClass: 'border-amber-500/35 text-amber-500/40'
  },
  'Bauchi Pearl (Teal watermark)': {
    layout: 'circle',
    stateName: 'BAUCHI STATE',
    slogan: 'PEARL OF TOURISM',
    primaryColor: '#0f766e',
    textColorClass: 'text-teal-900',
    borderColorClass: 'border-teal-600',
    fillColorClass: 'fill-teal-700',
    borderHex: '#0f766e',
    teethColorHex: '#0f766e',
    liaisonTitle: 'BAUCHI STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 4 PEARL WAY,', 'WUSE ZONE 5,', 'ABUJA'],
    crestEmoji: '🐚',
    traditionalRulerFallback: 'HRH Emir of Bauchi',
    stampText: 'BAUCHI LGA',
    stampColorClass: 'border-teal-600/35 text-teal-600/40'
  },
  'Bayelsa Pride (Navy blue border)': {
    layout: 'double',
    stateName: 'BAYELSA STATE',
    slogan: 'PRIDE OF THE NATION',
    primaryColor: '#172554',
    textColorClass: 'text-blue-950',
    borderColorClass: 'border-[#172554]',
    fillColorClass: 'fill-blue-900',
    borderHex: '#172554',
    teethColorHex: '#172554',
    liaisonTitle: 'BAYELSA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 12 OCEAN AVENUE,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '🦈',
    traditionalRulerFallback: 'HRH King of Nembe',
    stampText: 'BAYELSA',
    stampColorClass: 'border-blue-500/35 text-blue-500/40'
  },
  'Benue Food Basket (Green stripe)': {
    layout: 'teeth',
    stateName: 'BENUE STATE',
    slogan: 'FOOD BASKET OF THE NATION',
    primaryColor: '#15803d',
    textColorClass: 'text-green-900',
    borderColorClass: 'border-green-800',
    fillColorClass: 'fill-green-700',
    borderHex: '#15803d',
    teethColorHex: '#15803d',
    liaisonTitle: 'BENUE STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 22 BENUE WAY,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '🌽',
    traditionalRulerFallback: 'HRH Tor Tiv',
    stampText: 'BENUE DEPT',
    stampColorClass: 'border-green-500/35 text-green-500/40'
  },
  'Borno Home of Peace (Light blue border)': {
    layout: 'seal',
    stateName: 'BORNO STATE',
    slogan: 'HOME OF PEACE',
    primaryColor: '#0284c7',
    textColorClass: 'text-sky-950',
    borderColorClass: 'border-sky-800',
    fillColorClass: 'fill-sky-700',
    borderHex: '#0284c7',
    teethColorHex: '#0284c7',
    liaisonTitle: 'BORNO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 8 SAHEL WAY,', 'WUSE ZONE 4,', 'ABUJA'],
    crestEmoji: '🕌',
    traditionalRulerFallback: 'HRH Shehu of Borno',
    stampText: 'BORNO HQ',
    stampColorClass: 'border-sky-500/35 text-sky-550/40',
    sealColorHex: '#0284c7'
  },
  'Delta Big Heart (Red banner)': {
    layout: 'tricolor',
    stateName: 'DELTA STATE',
    slogan: 'THE BIG HEART',
    primaryColor: '#dc2626',
    textColorClass: 'text-red-950',
    borderColorClass: 'border-red-800',
    fillColorClass: 'fill-red-700',
    borderHex: '#dc2626',
    teethColorHex: '#dc2626',
    liaisonTitle: 'DELTA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 20 NIGER-DELTA AVENUE,', 'WUSE II,', 'ABUJA'],
    bannerColors: ['#047857', '#ffffff', '#dc2626'],
    crestEmoji: '❤️',
    traditionalRulerFallback: 'HRH Olu of Warri',
    stampText: 'DELTA GOVT',
    stampColorClass: 'border-red-500/40 text-red-650/50'
  },
  'Ebonyi Salt of the Nation (Slate double frame)': {
    layout: 'double',
    stateName: 'EBONYI STATE',
    slogan: 'SALT OF THE NATION',
    primaryColor: '#475569',
    textColorClass: 'text-slate-900',
    borderColorClass: 'border-slate-600',
    fillColorClass: 'fill-slate-700',
    borderHex: '#475569',
    teethColorHex: '#475569',
    liaisonTitle: 'EBONYI STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 6 SALT ROAD,', 'GARKI I,', 'ABUJA'],
    crestEmoji: '🧂',
    traditionalRulerFallback: 'HRH Eze of Abakaliki',
    stampText: 'EBONYI',
    stampColorClass: 'border-slate-500/35 text-slate-500/40'
  },
  'Edo Heartbeat (Red teeth border)': {
    layout: 'teeth',
    stateName: 'EDO STATE',
    slogan: 'HEARTBEAT OF THE NATION',
    primaryColor: '#991b1b',
    textColorClass: 'text-red-900',
    borderColorClass: 'border-red-900',
    fillColorClass: 'fill-red-850',
    borderHex: '#991b1b',
    teethColorHex: '#991b1b',
    liaisonTitle: 'EDO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 88 BRONZE STREET,', 'MAITAMA,', 'ABUJA'],
    crestEmoji: '👑',
    traditionalRulerFallback: 'HRH Oba of Benin',
    stampText: 'EDO STATE',
    stampColorClass: 'border-red-600/35 text-red-600/40'
  },
  'Ekiti Fountain of Knowledge (Green water certificate)': {
    layout: 'seal',
    stateName: 'EKITI STATE',
    slogan: 'LAND OF HONOUR & INTEGRITY',
    primaryColor: '#16a34a',
    textColorClass: 'text-green-850',
    borderColorClass: 'border-green-800',
    fillColorClass: 'fill-green-700',
    borderHex: '#16a34a',
    teethColorHex: '#16a34a',
    liaisonTitle: 'EKITI STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 30 HONOUR ROAD,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '⛲',
    traditionalRulerFallback: 'HRH Ewi of Ado Ekiti',
    stampText: 'EKITI AUTH',
    stampColorClass: 'border-green-500/35 text-green-500/40',
    sealColorHex: '#16a34a'
  },
  'Enugu Coal City (Black/gray seal)': {
    layout: 'double',
    stateName: 'ENUGU STATE',
    slogan: 'COAL CITY STATE',
    primaryColor: '#1e293b',
    textColorClass: 'text-slate-950',
    borderColorClass: 'border-slate-800',
    fillColorClass: 'fill-slate-900',
    borderHex: '#1e293b',
    teethColorHex: '#1e293b',
    liaisonTitle: 'ENUGU STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 5 COAL CRESCENT,', 'GARKI II,', 'ABUJA'],
    crestEmoji: '⛰️',
    traditionalRulerFallback: 'HRH Igwe of Nike',
    stampText: 'ENUGU AUTH',
    stampColorClass: 'border-slate-500/35 text-slate-500/40'
  },
  'FCT Abuja (Federal blue, tri-color emblem)': {
    layout: 'tricolor',
    stateName: 'FEDERAL CAPITAL TERRITORY',
    slogan: 'CENTRE OF UNITY',
    primaryColor: '#1d4ed8',
    textColorClass: 'text-blue-900',
    borderColorClass: 'border-blue-800',
    fillColorClass: 'fill-blue-700',
    borderHex: '#1d4ed8',
    teethColorHex: '#1d4ed8',
    liaisonTitle: 'FCT LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 10 UNITY DRIVE,', 'GARKI,', 'ABUJA'],
    bannerColors: ['#047857', '#ffffff', '#1d4ed8'],
    crestEmoji: '🏛️',
    traditionalRulerFallback: 'HRH Ona of Abaji',
    stampText: 'FCT SEC',
    stampColorClass: 'border-blue-500/40 text-blue-600/50'
  },
  'Gombe Jewel (Gold/purple border)': {
    layout: 'double',
    stateName: 'GOMBE STATE',
    slogan: 'JEWEL IN THE SAVANNAH',
    primaryColor: '#7c3aed',
    textColorClass: 'text-violet-950',
    borderColorClass: 'border-violet-600',
    fillColorClass: 'fill-violet-700',
    borderHex: '#7c3aed',
    teethColorHex: '#7c3aed',
    liaisonTitle: 'GOMBE STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 14 JEWEL CRESCENT,', 'WUSE ZONE 6,', 'ABUJA'],
    crestEmoji: '💎',
    traditionalRulerFallback: 'HRH Emir of Gombe',
    stampText: 'GOMBE CERT',
    stampColorClass: 'border-violet-500/35 text-violet-500/40'
  },
  'Jigawa New Horizon (Orange watermark)': {
    layout: 'seal',
    stateName: 'JIGAWA STATE',
    slogan: 'THE NEW HORIZON',
    primaryColor: '#ea580c',
    textColorClass: 'text-orange-950',
    borderColorClass: 'border-orange-850',
    fillColorClass: 'fill-orange-850',
    borderHex: '#ea580c',
    teethColorHex: '#ea580c',
    liaisonTitle: 'JIGAWA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 2 HORIZON AVENUE,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '🌅',
    traditionalRulerFallback: 'HRH Emir of Dutse',
    stampText: 'JIGAWA',
    stampColorClass: 'border-orange-550/35 text-orange-550/40',
    sealColorHex: '#ea580c'
  },
  'Kaduna Liberal State (Blue double circle)': {
    layout: 'circle',
    stateName: 'KADUNA STATE',
    slogan: 'CENTRE OF LEARNING',
    primaryColor: '#1e3a8a',
    textColorClass: 'text-blue-900',
    borderColorClass: 'border-blue-600',
    fillColorClass: 'fill-blue-700',
    borderHex: '#1e3a8a',
    teethColorHex: '#1e3a8a',
    liaisonTitle: 'KADUNA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 4 LEARNING CRESCENT,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '📖',
    traditionalRulerFallback: 'HRH Emir of Zazzau',
    stampText: 'KADUNA AUTH',
    stampColorClass: 'border-blue-600/35 text-blue-600/40'
  },
  'Kano Centre of Commerce (Red border)': {
    layout: 'teeth',
    stateName: 'KANO STATE',
    slogan: 'CENTRE OF COMMERCE',
    primaryColor: '#b91c1c',
    textColorClass: 'text-red-950',
    borderColorClass: 'border-red-900',
    fillColorClass: 'fill-red-800',
    borderHex: '#b91c1c',
    teethColorHex: '#b91c1c',
    liaisonTitle: 'KANO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 7 BIDA CRESCENT,', 'WUSE ZONE 3,', 'ABUJA'],
    crestEmoji: '🐎',
    traditionalRulerFallback: 'HRH Emir of Kano',
    stampText: 'KANO CERT',
    stampColorClass: 'border-red-500/35 text-red-500/40'
  },
  'Katsina Home of Hospitality (Amber border)': {
    layout: 'seal',
    stateName: 'KATSINA STATE',
    slogan: 'HOME OF HOSPITALITY',
    primaryColor: '#b45309',
    textColorClass: 'text-amber-950',
    borderColorClass: 'border-amber-800',
    fillColorClass: 'fill-amber-700',
    borderHex: '#b45309',
    teethColorHex: '#b45309',
    liaisonTitle: 'KATSINA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 9 COVENANT WAY,', 'WUSE ZONE 2,', 'ABUJA'],
    crestEmoji: '🎴',
    traditionalRulerFallback: 'HRH Emir of Katsina',
    stampText: 'KATSINA',
    stampColorClass: 'border-amber-500/35 text-amber-500/40',
    sealColorHex: '#b45309'
  },
  'Kebbi Land of Equity (Green double circle)': {
    layout: 'circle',
    stateName: 'KEBBI STATE',
    slogan: 'LAND OF EQUITY',
    primaryColor: '#15803d',
    textColorClass: 'text-green-900',
    borderColorClass: 'border-green-600',
    fillColorClass: 'fill-green-700',
    borderHex: '#15803d',
    teethColorHex: '#15803d',
    liaisonTitle: 'KEBBI STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 15 EQUAL AVENUE,', 'WUSE ZONE 1,', 'ABUJA'],
    crestEmoji: '⚖️',
    traditionalRulerFallback: 'HRH Emir of Gwandu',
    stampText: 'KEBBI AUTH',
    stampColorClass: 'border-green-600/35 text-green-600/40'
  },
  'Kogi Confluence (Slate blue ribbon)': {
    layout: 'tricolor',
    stateName: 'KOGI STATE',
    slogan: 'THE CONFLUENCE STATE',
    primaryColor: '#475569',
    textColorClass: 'text-slate-900',
    borderColorClass: 'border-slate-700',
    fillColorClass: 'fill-slate-600',
    borderHex: '#475569',
    teethColorHex: '#475569',
    liaisonTitle: 'KOGI STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 33 RIVER LIGAMENT,', 'WUSE II,', 'ABUJA'],
    bannerColors: ['#0284c7', '#ffffff', '#15803d'],
    crestEmoji: '🌁',
    traditionalRulerFallback: 'HRH Attah of Igala',
    stampText: 'KOGI COV',
    stampColorClass: 'border-slate-500/40 text-slate-650/50'
  },
  'Kwara State of Harmony (Gold seal)': {
    layout: 'teeth',
    stateName: 'KWARA STATE',
    slogan: 'LIAISON OFFICE HARMONY',
    primaryColor: '#d97706',
    textColorClass: 'text-amber-950',
    borderColorClass: 'border-amber-800',
    fillColorClass: 'fill-amber-700',
    borderHex: '#d97706',
    teethColorHex: '#d97706',
    liaisonTitle: 'KWARA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 45 PROGRESS STREET,', 'MAITAMA,', 'ABUJA'],
    crestEmoji: '🏺',
    traditionalRulerFallback: 'HRH Emir of Ilorin',
    stampText: 'KWARA AUTH',
    stampColorClass: 'border-amber-500/35 text-amber-500/40'
  },
  'Nasarawa Home of Solid Minerals (Double brown frame)': {
    layout: 'double',
    stateName: 'NASARAWA STATE',
    slogan: 'HOME OF SOLID MINERALS',
    primaryColor: '#7c2d12',
    textColorClass: 'text-orange-950',
    borderColorClass: 'border-orange-850',
    fillColorClass: 'fill-orange-850',
    borderHex: '#7c2d12',
    teethColorHex: '#7c2d12',
    liaisonTitle: 'NASARAWA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 70 MINERAL DRIVE,', 'GARKI I,', 'ABUJA'],
    crestEmoji: '⛏️',
    traditionalRulerFallback: 'HRH Emir of Lafia',
    stampText: 'NASARAWA',
    stampColorClass: 'border-orange-500/35 text-orange-500/40'
  },
  'Niger Power State (Red/gold border)': {
    layout: 'double',
    stateName: 'NIGER STATE',
    slogan: 'THE POWER STATE',
    primaryColor: '#dc2626',
    textColorClass: 'text-red-950',
    borderColorClass: 'border-[#dc2626]',
    fillColorClass: 'fill-red-800',
    borderHex: '#dc2626',
    teethColorHex: '#dc2626',
    liaisonTitle: 'NIGER STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 11 BOSSO STREET,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '⚡',
    traditionalRulerFallback: 'HRH Emir of Minna',
    stampText: 'NIGER AUTH',
    stampColorClass: 'border-red-500/35 text-red-500/40'
  },
  'Ogun Gateway State (Blue ribbon strip)': {
    layout: 'tricolor',
    stateName: 'OGUN STATE',
    slogan: 'GATEWAY STATE',
    primaryColor: '#2563eb',
    textColorClass: 'text-blue-900',
    borderColorClass: 'border-blue-700',
    fillColorClass: 'fill-blue-600',
    borderHex: '#2563eb',
    teethColorHex: '#2563eb',
    liaisonTitle: 'OGUN STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 14 GATEWAY CRESCENT,', 'WUSE II,', 'ABUJA'],
    bannerColors: ['#2563eb', '#ffffff', '#15803d'],
    crestEmoji: '🚪',
    traditionalRulerFallback: 'HRH Alake of Egbaland',
    stampText: 'OGUN STATE',
    stampColorClass: 'border-blue-500/40 text-blue-600/50'
  },
  'Osun State of the Living Spring (Blue water seal)': {
    layout: 'seal',
    stateName: 'OSUN STATE',
    slogan: 'STATE OF THE LIVING SPRING',
    primaryColor: '#2563eb',
    textColorClass: 'text-blue-950',
    borderColorClass: 'border-blue-800',
    fillColorClass: 'fill-blue-700',
    borderHex: '#2563eb',
    teethColorHex: '#2563eb',
    liaisonTitle: 'OSUN STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 5 SPRING STREET,', 'WUSE ZONE 5,', 'ABUJA'],
    crestEmoji: '⛲',
    traditionalRulerFallback: 'HRH Ooni of Ife',
    stampText: 'OSUN AUTH',
    stampColorClass: 'border-blue-500/35 text-blue-500/40',
    sealColorHex: '#2563eb'
  },
  'Oyo Pace Setter (Maroon ribbon)': {
    layout: 'tricolor',
    stateName: 'OYO STATE',
    slogan: 'PACE SETTER STATE',
    primaryColor: '#9d174d',
    textColorClass: 'text-pink-950',
    borderColorClass: 'border-pink-800',
    fillColorClass: 'fill-pink-700',
    borderHex: '#9d174d',
    teethColorHex: '#9d174d',
    liaisonTitle: 'OYO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 15 PACE STREET,', 'GARKI ZONE II,', 'ABUJA'],
    bannerColors: ['#9d174d', '#ffffff', '#b45309'],
    crestEmoji: '🎯',
    traditionalRulerFallback: 'HRH Alaafin of Oyo',
    stampText: 'OYO STATE',
    stampColorClass: 'border-pink-500/40 text-pink-600/50'
  },
  'Plateau Home of Peace & Tourism (Green border)': {
    layout: 'double',
    stateName: 'PLATEAU STATE',
    slogan: 'HOME OF PEACE & TOURISM',
    primaryColor: '#15803d',
    textColorClass: 'text-green-950',
    borderColorClass: 'border-green-600',
    fillColorClass: 'fill-green-750',
    borderHex: '#15803d',
    teethColorHex: '#15803d',
    liaisonTitle: 'PLATEAU STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 29 COLD AVENUE,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '🏔️',
    traditionalRulerFallback: 'HRH Gbong Gwom Jos',
    stampText: 'PLATEAU',
    stampColorClass: 'border-green-500/35 text-green-500/40'
  },
  'Rivers Treasure Base (Crimson double frame)': {
    layout: 'double',
    stateName: 'RIVERS STATE',
    slogan: 'TREASURE BASE OF THE NATION',
    primaryColor: '#b91c1c',
    textColorClass: 'text-red-950',
    borderColorClass: 'border-red-950',
    fillColorClass: 'fill-red-850',
    borderHex: '#b91c1c',
    teethColorHex: '#b91c1c',
    liaisonTitle: 'RIVERS STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 49 TREASURE BOULEVARD,', 'GARKI II,', 'ABUJA'],
    crestEmoji: '🛡️',
    traditionalRulerFallback: 'HRH King Jaja of Opobo',
    stampText: 'RIVERS CIV',
    stampColorClass: 'border-red-500/35 text-red-500/40'
  },
  'Sokoto Caliphate (Black ribbon border)': {
    layout: 'circle',
    stateName: 'SOKOTO STATE',
    slogan: 'SEAT OF THE CALIPHATE',
    primaryColor: '#1e293b',
    textColorClass: 'text-slate-950',
    borderColorClass: 'border-slate-900',
    fillColorClass: 'fill-slate-800',
    borderHex: '#1e293b',
    teethColorHex: '#1e293b',
    liaisonTitle: 'SOKOTO STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 7 CALIPHATE STREET,', 'WUSE II,', 'ABUJA'],
    crestEmoji: '☪️',
    traditionalRulerFallback: 'HRH Sultan of Sokoto',
    stampText: 'SOKOTO HQ',
    stampColorClass: 'border-slate-600/35 text-slate-600/40'
  },
  'Taraba Nature\'s Gift (Gold double thin frame)': {
    layout: 'double',
    stateName: 'TARABA STATE',
    slogan: 'NATURE\'S GIFT TO THE NATION',
    primaryColor: '#d97706',
    textColorClass: 'text-amber-950',
    borderColorClass: 'border-amber-600',
    fillColorClass: 'fill-amber-700',
    borderHex: '#d97706',
    teethColorHex: '#d97706',
    liaisonTitle: 'TARABA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 29 SAHEL CRESCENT,', 'WUSE ZONE 6,', 'ABUJA'],
    crestEmoji: '🌲',
    traditionalRulerFallback: 'HRH Aku Uka of Wukari',
    stampText: 'TARABA SEC',
    stampColorClass: 'border-amber-500/35 text-amber-500/40'
  },
  'Yobe Pride of the Sahel (Khaki seal)': {
    layout: 'seal',
    stateName: 'YOBE STATE',
    slogan: 'PRIDE OF THE SAHEL',
    primaryColor: '#7c2d12',
    textColorClass: 'text-red-950',
    borderColorClass: 'border-red-950',
    fillColorClass: 'fill-red-900',
    borderHex: '#7c2d12',
    teethColorHex: '#7c2d12',
    liaisonTitle: 'YOBE STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 11 SAHEL ROAD,', 'WUSE ZONE 4,', 'ABUJA'],
    crestEmoji: '🌾',
    traditionalRulerFallback: 'HRH Emir of Fika',
    stampText: 'YOBE GOVT',
    stampColorClass: 'border-orange-500/35 text-orange-550/40',
    sealColorHex: '#7c2d12'
  },
  'Zamfara Farming is our Pride (Green/gold banner)': {
    layout: 'tricolor',
    stateName: 'ZAMFARA STATE',
    slogan: 'FARMING IS OUR PRIDE',
    primaryColor: '#15803d',
    textColorClass: 'text-green-900',
    borderColorClass: 'border-green-700',
    fillColorClass: 'fill-green-600',
    borderHex: '#15803d',
    teethColorHex: '#15803d',
    liaisonTitle: 'ZAMFARA STATE LIAISON OFFICE',
    liaisonAddressLines: ['PLOT 15 FARM CRESCENT,', 'WUSE II,', 'ABUJA'],
    bannerColors: ['#047857', '#ffffff', '#ea580c'],
    crestEmoji: '🐄',
    traditionalRulerFallback: 'HRH Emir of Anka',
    stampText: 'ZAMFARA',
    stampColorClass: 'border-green-500/40 text-green-600/50'
  }
};

export function getPresetConfig(stylePreset: string): PresetConfig {
  const original = PRESETS_DB[stylePreset] || PRESETS_DB['Imo Heartland (Green teeth border)'];
  
  // Decide dynamically based on the stylePreset title if it represents a Green or Black theme
  // This alternates between deep black-and-white high-contrast, and vibrant white-and-green
  const isGreen = stylePreset.toLowerCase().includes('green') || 
                  stylePreset.toLowerCase().includes('oguta') || 
                  stylePreset.toLowerCase().includes('heartland') ||
                  stylePreset.toLowerCase().includes('savannah') ||
                  stylePreset.toLowerCase().includes('harmony') ||
                  stylePreset.toLowerCase().includes('spring') ||
                  stylePreset.toLowerCase().includes('tourism') ||
                  stylePreset.toLowerCase().includes('farming') ||
                  stylePreset.toLowerCase().includes('knowledge') ||
                  stylePreset.toLowerCase().includes('confluence') ||
                  stylePreset.length % 2 === 0;

  const primary = isGreen ? '#00c060' : '#000000';
  
  return {
    ...original,
    primaryColor: primary,
    textColorClass: isGreen ? 'text-[#00c060]' : 'text-black',
    borderColorClass: isGreen ? 'border-[#00c060]' : 'border-black',
    fillColorClass: isGreen ? 'fill-[#00c060]' : 'fill-black',
    borderHex: primary,
    teethColorHex: primary,
    bannerColors: ['#000000', '#ffffff', '#00c060'],
    stampColorClass: isGreen ? 'border-[#00c060]/50 text-[#00c060]/60' : 'border-black/50 text-black/60',
    sealColorHex: primary
  };
}
